### ISSUE TITLE
Could not compile shader error. 

### ISSUE THREAD

**Issue by Q2Flc2Fy** [Silorex/silorex#1]
Using jdk-9.0.4.jdk, didn't modify anything in the code. 
From the console: 
Connected to the target VM, address: '127.0.0.1:52114', transport: 'socket'
Could not compile shader!
ERROR: 0:1: '' :  version '400' is not supported
ERROR: 0:1: '' : syntax error: #version

Disconnected from the target VM, address: '127.0.0.1:52114', transport: 'socket'

Process finished with exit code 255

**Comment by marxt12372** [comment]
Your graphics card does not support OpenGL 4.

**Comment by Q2Flc2Fy** [comment]
It does MacBook Pro (Retina, 15-inch, Mid 2014) https://support.apple.com/en-us/HT202823, maybe I have a problem with the run configuration though.

**Comment by Q2Flc2Fy** [comment]
Wait, sorry you were right, apples support site is wrong. OpenGL version string: 2.1 , meaning it can only go up to #version 110. Sorry :/
